version: '3'

services:
  gobarber-api:
    build: .
    image: thehiddenbuddy/gobarber-api:latest
    container_name: gobarber-api
    volumes:
      - .:/home/node/api
    environment:
      - NODE_ENV=development
      - DB_HOST=gobarber-postgres
      - MONGO_URL=mongodb://gobarber-mongo:27017/gobarber
    restart: always
    ports:
      - '3333:3333'
    depends_on:
      - gobarber-postgres
      - gobarber-mongo
      - gobarber-redis
    networks:
      - gobarber-network

  gobarber-postgres:
    image: postgres
    container_name: gobarber-postgres
    restart: always
    environment:
      - DB_HOST=gobarber-postgres
      - POSTGRES_USER:${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - gobarber-postgres-data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    networks:
      - gobarber-network

  gobarber-mongo:
    image: mongo
    container_name: gobarber-mongo
    restart: always
    volumes:
      - gobarber-mongo-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - gobarber-network

  gobarber-redis:
    image: bitnami/redis:latest
    container_name: gobarber-redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - gobarber-redis-data:/data
    ports:
      - '6379:6379'
    networks:
      - gobarber-network

volumes:
  gobarber-postgres-data:
  gobarber-mongo-data:
  gobarber-redis-data:

networks:
  gobarber-network:
    driver: bridge
